/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger KazUSA API
 * This is the KazUSA server.
 * OpenAPI spec version: 1.0
 */

export interface KazusaServerInternalEntityModule {
  content?: string;
  courseId?: string;
  createdAt?: string;
  durationMinutes?: number;
  id?: string;
  name?: string;
  updatedAt?: string;
}
