/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger KazUSA API
 * This is the KazUSA server.
 * OpenAPI spec version: 1.0
 */
import type { KazusaServerInternalEntityModuleFilters } from './kazusaServerInternalEntityModuleFilters';
import type { KazusaServerInternalEntityPagination } from './kazusaServerInternalEntityPagination';

export interface KazusaServerInternalEntityModuleReadRequest {
  filters?: KazusaServerInternalEntityModuleFilters;
  pagination?: KazusaServerInternalEntityPagination;
}
