/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger KazUSA API
 * This is the KazUSA server.
 * OpenAPI spec version: 1.0
 */
import type { KazusaServerInternalEntityCourseFilters } from './kazusaServerInternalEntityCourseFilters';
import type { KazusaServerInternalEntityPagination } from './kazusaServerInternalEntityPagination';

export interface KazusaServerInternalEntityCourseReadRequest {
  filters?: KazusaServerInternalEntityCourseFilters;
  pagination?: KazusaServerInternalEntityPagination;
}
