/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger KazUSA API
 * This is the KazUSA server.
 * OpenAPI spec version: 1.0
 */

export interface KazusaServerInternalEntityPagination {
  limit?: number;
  offset?: number;
}
